name: film_rehberi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Standart İkon seti
  cupertino_icons: ^1.0.8

  # --- PROJE PAKETLERİ ---
  
  # 1. API Bağlantısı
  http: ^1.2.0

  # 2. Resim Önbellekleme
  cached_network_image: ^3.3.1

  # 3. Yazı Tipleri
  google_fonts: ^6.1.0

  # 4. Veritabanı (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 5. Link ve Fragman Açma (YENİ EKLENDİ)
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- GELİŞTİRİCİ ARAÇLARI ---
  
  # Hive Kod Üreticileri
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # Uygulama İkonu Değiştirici
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- İKON AYARLARI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21